# Generated by Django 6.1.1 on 2026-09-24 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCardModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('streaming', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentInterfaceModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('protocol_binding', models.CharField(choices=[('HTTP+JSON', 'Http Json'), ('JSONRPC', 'Jsonrpc'), ('GRPC', 'Grpc')], default='JSONRPC', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentSkillModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentExecutorModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('rpc_url', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='protocol.agentcardmodel')),
                ('excluded_internal_tools', models.ManyToManyField(blank=True, to='agent.internaltool')),
                ('llm_config', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.llmconfig')),
                ('mcp_servers', models.ManyToManyField(blank=True, related_name='agents', to='agent.mcpserverconfig')),
                ('skills', models.ManyToManyField(blank=True, related_name='agents', to='agent.skill')),
                ('system_prompt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.systemprompt')),
                ('thread_config', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.threadconfig')),
            ],
        ),
        migrations.AddField(
            model_name='agentcardmodel',
            name='supported_interfaces',
            field=models.ManyToManyField(blank=True, related_name='agent_cards', to='protocol.agentinterfacemodel'),
        ),
        migrations.AddField(
            model_name='agentcardmodel',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='protocol.agentskillmodel'),
        ),
        migrations.AddField(
            model_name='agentskillmodel',
            name='examples',
            field=models.ManyToManyField(blank=True, related_name='agent_skills', to='protocol.skillexample'),
        ),
        migrations.AddField(
            model_name='agentskillmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='agent_skills', to='protocol.skilltag'),
        ),
    ]
