# Generated by Django 6.1.1 on 2026-09-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentinterfacemodel',
            name='url',
        ),
        migrations.AddField(
            model_name='agentinterfacemodel',
            name='host',
            field=models.CharField(default='127.0.0.1', max_length=20),
        ),
        migrations.AddField(
            model_name='agentinterfacemodel',
            name='port',
            field=models.IntegerField(default=8000),
        ),
    ]
