# Generated by Django 6.1.1 on 2026-09-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'Openai'), ('openai-compatible', 'Openai Compatible'), ('open-router', 'Open Router')], default='openai-compatible', max_length=100),
        ),
        migrations.AlterField(
            model_name='threadconfig',
            name='compression_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agent.compressionprompt'),
        ),
        migrations.AlterField(
            model_name='threadconfig',
            name='system_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agent.systemprompt'),
        ),
    ]
