# Generated by Django 6.1.1 on 2026-09-25 05:45

import colorfield.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTheme',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('deep', colorfield.fields.ColorField(default='#202121', image_field=None, max_length=25, samples=None)),
                ('mid', colorfield.fields.ColorField(default='#3D4242', image_field=None, max_length=25, samples=None)),
                ('accent', colorfield.fields.ColorField(default='#8A8D8D', image_field=None, max_length=25, samples=None)),
                ('sand', colorfield.fields.ColorField(default='#B5AF99', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('mcp-server', 'Mcp Server'), ('llm-config', 'Llm Config'), ('thread-config', 'Thread Config'), ('agent-skill', 'Agent Skill'), ('agent-interface', 'Agent Interface'), ('agent-card', 'Agent Card'), ('agent-executor', 'Agent Executor'), ('server-stack', 'Server Stack')], default='agent-executor', max_length=30)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('color_code', colorfield.fields.ColorField(default='#47B9B9', image_field=None, max_length=25, samples=None)),
                ('component_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('type', models.TextField(choices=[('agent-executor', 'Agent Executor'), ('a2a', 'A2A')], default='a2a', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing', to='dnd.component')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming', to='dnd.component')),
            ],
        ),
        migrations.CreateModel(
            name='ServerStack',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servers', models.ManyToManyField(blank=True, related_name='stack', to='agent.mcpserverconfig')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.workspace'),
        ),
    ]
