# Generated by Django 6.1.1 on 2026-09-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='workspace',
        ),
        migrations.AddField(
            model_name='workspace',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='workspace', to='dnd.component'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='workspace', to='dnd.connection'),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
