# Generated by Django 6.1.1 on 2026-09-28 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_remove_component_workspace_workspace_components_and_more'),
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.TextField(choices=[('mcp-server', 'Mcp Server'), ('llm-config', 'Llm Config'), ('thread-config', 'Thread Config'), ('agent-skill', 'Agent Skill'), ('agent-interface', 'Agent Interface'), ('agent-card', 'Agent Card'), ('agent-executor', 'Agent Executor'), ('server-stack', 'Server Stack'), ('agent-skill-stack', 'Agent Skill Stack'), ('agent-interface-stack', 'Agent Interface Stack')], default='agent-executor', max_length=30),
        ),
        migrations.CreateModel(
            name='AgentInterfaceStack',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_interfaces', models.ManyToManyField(blank=True, related_name='stacks', to='protocol.agentinterfacemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AgentSkillStack',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_skills', models.ManyToManyField(blank=True, related_name='stack', to='protocol.agentskillmodel')),
            ],
        ),
    ]
